### ISSUE TITLE
Simplify the build

### ISSUE THREAD

**Issue by ForNeVeR** [morganey-lang/morganey-intellij-plugin#10]
Currently, to build the plugin, I have to mess with the IDEA settings all the way:
- set up IDEA SDK directly in [`misc.xml`](https://github.com/morganey-lang/morganey-intellij-plugin/blob/323df1fadc39d8218c357bff9b8f3e1ccc805eb1/.idea/misc.xml#L48)
- mess with Scala SDK settings because it cannot install it automatically for some reason
- replace Morganey artifacts manually in case I want to use modified or newly released version

Moreover, I can't see a way to automate the project build on Travis / Appveyor currently.

All these issues have a common source: lack of dependency management system for the currently used project model (plain [IML file](https://github.com/morganey-lang/morganey-intellij-plugin/blob/323df1fadc39d8218c357bff9b8f3e1ccc805eb1/morganey-intellij-plugin.iml) in the project root and [a bunch of stuff](https://github.com/morganey-lang/morganey-intellij-plugin/tree/323df1fadc39d8218c357bff9b8f3e1ccc805eb1/.idea) in `.idea` directory).

I think it's a good idea to use something like [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin). That way, a project won't require the IDEA to build it (although it'll obviously still be required to actually use the plugin). And I hope that it'll not break the current development experience very much: it should still be easy to develop the project using IDEA.

@rexim, @keddelzz, @06needhamt, I welcome you guys to discuss that.

**Comment by rexim** [comment]
I completely agree with you. When I developed for Eclipse RCP the workflow was similar to what you've described. Locally it was pure Eclipse. On CI it was Maven Tycho. Nothing else to add from my side. :)

**Comment by 06needhamt** [comment]
@ForNeVeR I Completely agree also. However Im not entirely sure how to set this up. I Would also like to use a similar approach for my https://github.com/06needhamt/Neuroph-Intellij-Plugin See issue https://github.com/06needhamt/Neuroph-Intellij-Plugin/issues/7 for details on my thoughts

**Comment by 06needhamt** [comment]
@rexim @keddelzz @ForNeVeR Hi guys I have created a semi-working Gradle build system on the [new-build](https://github.com/morganey-lang/morganey-intellij-plugin/tree/new-build) branch however there is one issue with it see [this issue](https://github.com/morganey-lang/morganey-intellij-plugin/issues/13)

**Comment by 06needhamt** [comment]
I have also deleted that repository i created earlier apologies for the inconvenience

**Comment by rexim** [comment]
> I have also deleted that repository i created earlier apologies for the inconvenience

It's ok. No worries. It was actually my fault. I was expecting something like this to happen and was planning to include this situation into the draft of rules. I should've finish the rules as soon as possible. I'll try to finish the rules tomorrow and will present them for the review and discussion.

My intentions are to keep the organization clean. Suddenly appearing for no reason repos can easily clutter the entire organization. It doesn't mean we should not create new repos. New repos are always welcome. We just need to be sure that it is clear for everyone why those repos exist here. In case of Morganey-Jar it was completely unclear for me because of https://github.com/morganey-lang/Morganey/issues/210#issuecomment-249643887 :) I disabled repo creations for the members.

Please next time if you need a repo in the @morganey-lang organization, just file an issue at https://github.com/morganey-lang/organization with brief explanation why you need that repo and we will do our best to help you with your request.

**Comment by 06needhamt** [comment]
@rexim No Problem it will not happen again :)

@ForNeVeR @rexim @keddelzz When you guys get time could you please check that the Gradle System works for you so we can hopefully find a fix for #13

**Comment by ForNeVeR** [comment]
@06needhamt I'll try to take a look at #13. Thank you.

**Comment by 06needhamt** [comment]
Closed #14
